import type {
  AgentActionLog,
  AthleteToken,
  FutureAssetClass,
  LaCasaDepositRecord,
  SophiaAgent,
  VaultSummary,
} from './types';

export const starterVaults: VaultSummary[] = [
  {
    id: 'vault-echo-foundation',
    name: 'Echo Protocol Vault',
    assetType: 'dapp_equity',
    depositedAmount: 142500,
    vaultValue: 159820,
    policy: 'growth',
    circuitState: 'normal',
    assignedAgent: 'Sophia Sentinel',
    laCasaDeposits: 24,
    athleteExposure: 118000,
    protectiveBuffer: 11.4,
  },
  {
    id: 'vault-worldlabs-rwa',
    name: 'World Labs Expansion Vault',
    assetType: 'real_estate',
    depositedAmount: 38500,
    vaultValue: 40120,
    policy: 'balanced',
    circuitState: 'warning',
    assignedAgent: 'Sophia Yield',
    laCasaDeposits: 6,
    athleteExposure: 0,
    protectiveBuffer: 15.8,
  },
];

export const starterAthleteTokens: AthleteToken[] = [
  {
    id: 'token-cdubb',
    symbol: '$CDUBB',
    name: 'C Dubb',
    price: 18.42,
    changePct: 8.4,
    exposure: 52000,
    valueGrowthPct: 24.6,
    trainingScore: 91,
    statsIndex: 88,
    nilRewards: 6300,
    streak: 11,
    vaultId: 'vault-echo-foundation',
    kingSignal: 'accelerate',
    suggestions: [
      {
        id: 'cdubb-drills',
        title: 'Explosive finishing block',
        focus: 'training',
        rationale: 'Rim pressure is converting at a higher clip than perimeter reps. Keep the edge compounding.',
        expectedImpactBps: 180,
        status: 'queued',
      },
      {
        id: 'cdubb-nil',
        title: 'Weekend NIL drop',
        focus: 'nil',
        rationale: 'Training streak momentum supports a short, premium social activation window.',
        expectedImpactBps: 90,
        status: 'queued',
      },
    ],
  },
  {
    id: 'token-ajwill',
    symbol: '$AJWILL',
    name: 'AJ Will',
    price: 14.76,
    changePct: 5.1,
    exposure: 38000,
    valueGrowthPct: 18.2,
    trainingScore: 86,
    statsIndex: 83,
    nilRewards: 4120,
    streak: 8,
    vaultId: 'vault-echo-foundation',
    kingSignal: 'build',
    suggestions: [
      {
        id: 'ajwill-shooting',
        title: 'Corner shooting ladder',
        focus: 'stats',
        rationale: 'Corner efficiency is the cleanest path to a faster valuation multiple lift.',
        expectedImpactBps: 140,
        status: 'queued',
      },
      {
        id: 'ajwill-strength',
        title: 'Lower-body strength phase',
        focus: 'training',
        rationale: 'The current workload supports a short power block without volatility in game output.',
        expectedImpactBps: 110,
        status: 'queued',
      },
    ],
  },
  {
    id: 'token-athlete',
    symbol: '$ATHLETE',
    name: 'Athlete',
    price: 11.93,
    changePct: 11.8,
    exposure: 28000,
    valueGrowthPct: 27.4,
    trainingScore: 94,
    statsIndex: 90,
    nilRewards: 5085,
    streak: 13,
    vaultId: 'vault-echo-foundation',
    kingSignal: 'protect',
    suggestions: [
      {
        id: 'athlete-recovery',
        title: 'Recovery-biased skill split',
        focus: 'training',
        rationale: 'Momentum is strong enough to prioritize preservation before the next acceleration window.',
        expectedImpactBps: 95,
        status: 'queued',
      },
      {
        id: 'athlete-brand',
        title: 'Brand-safe NIL cadence',
        focus: 'nil',
        rationale: 'Keep sponsor attention high while reducing overtraining risk into the next event cycle.',
        expectedImpactBps: 120,
        status: 'queued',
      },
    ],
  },
];

export const starterLaCasaDeposits: LaCasaDepositRecord[] = [
  {
    id: 'lacasa-1',
    label: 'La Casa Genesis #014',
    collection: 'La Casa Genesis',
    stablecoinAmount: 12500,
    vaultId: 'vault-echo-foundation',
    athleteTokenId: 'token-cdubb',
    depositedAt: '2026-03-17T14:30:00.000Z',
  },
  {
    id: 'lacasa-2',
    label: 'La Casa Athlete Series #031',
    collection: 'La Casa Athlete Series',
    stablecoinAmount: 8200,
    vaultId: 'vault-echo-foundation',
    athleteTokenId: 'token-hailee',
    depositedAt: '2026-03-18T09:05:00.000Z',
  },
];

export const starterFutureAssetClasses: FutureAssetClass[] = [
  {
    id: 'future-dapp-equity',
    title: 'DApp Equity Foundation',
    description: 'Tokenized exposure to top-tier Bags ecosystem protocols (Abraxas, LuckyFee AI, OCCUPY, Orbis API, JackBuilds, Cluck Norris, Hive, Trenchy.fun, quAId, Agent Inc.) with integrated yield routing and automated rebalancing.',
    status: 'coming_soon',
  },
  {
    id: 'future-real-estate',
    title: 'Real Estate Development',
    description: 'Renovation upgrades, rent yield, and occupancy quality become the development loop that grows property-backed vault value.',
    status: 'coming_soon',
  },
  {
    id: 'future-trading',
    title: 'Trading Portfolios',
    description: 'King AI can later optimize portfolio discipline, execution quality, and risk-adjusted returns using the same growth mechanics.',
    status: 'blueprint',
  },
];

export const starterLogs: AgentActionLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-03-18T12:00:00.000Z',
    vaultId: 'vault-echo-foundation',
    action: 'King AI refreshed dapp equity guidance',
    detail: 'Protocol yield curves and M1 pulldown mechanics were repriced across the Sophia\'s Family basket.',
  },
  {
    id: 'log-2',
    timestamp: '2026-03-18T13:15:00.000Z',
    vaultId: 'vault-worldlabs-rwa',
    action: 'Circuit protective payout staged',
    detail: 'Expansion Vault widened its buffer after volatility crossed warning thresholds.',
  },
];

export const starterSophiaAgents: SophiaAgent[] = [
  {
    id: 'sophia-sentinel',
    name: 'Sophia Sentinel',
    description: 'Defensive dapp equity specialist with emphasis on downside protection and circuit activation.',
    personality: 'conservative',
    specialty: 'DApp Equity Risk Management',
    status: 'active',
    tradingStyle: 'Mean-reversion focused with tight stops',
    riskTolerance: 'low',
    totalTradesExecuted: 156,
    totalVolumeTraded: 2840000,
    totalPnL: 156800,
    winRate: 64.1,
    averageReturnBps: 55,
    performanceScore: 82,
    createdAt: '2025-11-15T08:00:00.000Z',
    lastTradeAt: '2026-03-19T10:30:00.000Z',
    monthlyWinRate: 68.5,
    sharpeRatio: 1.8,
    maxDrawdown: -8.2,
    assignedToVaults: ['vault-echo-foundation'],
    mintedTokenAmount: 500000,
  },
  {
    id: 'sophia-yield',
    name: 'Sophia Yield',
    description: 'Real estate and income-focused agent optimizing for stable cash flow.',
    personality: 'balanced',
    specialty: 'RWA Yield Optimization',
    status: 'active',
    tradingStyle: 'Carry and dividend harvesting with rebalancing',
    riskTolerance: 'medium',
    totalTradesExecuted: 89,
    totalVolumeTraded: 1920000,
    totalPnL: 98400,
    winRate: 71.8,
    averageReturnBps: 51,
    performanceScore: 79,
    createdAt: '2025-12-01T14:00:00.000Z',
    lastTradeAt: '2026-03-18T15:45:00.000Z',
    monthlyWinRate: 74.2,
    sharpeRatio: 1.6,
    maxDrawdown: -6.1,
    assignedToVaults: ['vault-worldlabs-rwa'],
    mintedTokenAmount: 350000,
  },
  {
    id: 'sophia-momentum',
    name: 'Sophia Momentum',
    description: 'Growth-oriented trader capturing dapp equity upside momentum.',
    personality: 'aggressive',
    specialty: 'DApp Equity Momentum Trading',
    status: 'active',
    tradingStyle: 'Trend-following with breakout execution',
    riskTolerance: 'high',
    totalTradesExecuted: 203,
    totalVolumeTraded: 4120000,
    totalPnL: 287600,
    winRate: 58.6,
    averageReturnBps: 70,
    performanceScore: 85,
    createdAt: '2025-10-20T11:00:00.000Z',
    lastTradeAt: '2026-03-19T09:15:00.000Z',
    monthlyWinRate: 62.1,
    sharpeRatio: 1.4,
    maxDrawdown: -14.8,
    assignedToVaults: [],
    mintedTokenAmount: 750000,
  },
  {
    id: 'sophia-arbitrage',
    name: 'Sophia Arbitrage',
    description: 'Cross-asset arbitrage specialist finding inefficiencies across RWA pairs.',
    personality: 'balanced',
    specialty: 'Cross-Market RWA Arbitrage',
    status: 'training',
    tradingStyle: 'Statistical arbitrage with market-neutral hedges',
    riskTolerance: 'medium',
    totalTradesExecuted: 45,
    totalVolumeTraded: 892000,
    totalPnL: 32400,
    winRate: 84.4,
    averageReturnBps: 36,
    performanceScore: 71,
    createdAt: '2026-01-15T10:00:00.000Z',
    lastTradeAt: '2026-03-17T16:20:00.000Z',
    monthlyWinRate: 86.7,
    sharpeRatio: 2.1,
    maxDrawdown: -3.2,
    assignedToVaults: [],
  },
];
